version: '2'
services:

  rabbitmq:
    image: rabbitmq:3.6
    network_mode: "bridge"

  db:
    image: kartoza/postgis:9.6-2.4
    restart: on-failure
    volumes:
      - './pg/postgres_data:/var/lib/postgresql'
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=gis
      - POSTGRES_PASS=docker
    network_mode: "bridge"

  django:
    build: docker-geonode
    volumes:
      - '../src/geonode:/usr/src/app'
      - '../src/core:/usr/src/core'
      - '../src/geonode/geonode/static_root:/home/web/static'
      - '../src/geonode/geonode/uploaded:/home/web/media'
      - './geonode_backup:/geonode_backup'
      - './logs:/var/log/'
    command: prod
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - GEOSERVER_BASE_URL="http://geoserver:8080/geoserver/"
# Should be specified in docker-compose.override.yml. Because it depends on the
# host
#      - ALLOWED_HOSTS=['django',]
      - DEBUG=False
      - DATABASE_URL=postgres://gis:docker@db:5432/gis
      - GEODATABASE_URL=postgres://gis:docker@db:5432/gis
      - PYTHONPATH=/usr/src:/usr/src/app/
      - DJANGO_SETTINGS_MODULE=core.settings
      - ROOT_URLCONF=core.urls
      - SITEURL=http://localhost/
      - GEONODE_BASE_URL=http://nginx/
      - QGIS_SERVER_URL=http://qgis-server/
      - GEONODE_DATABASE_PASSWORD=docker
      - GEONODE_DATABASE=gis
      - GEONODE_GEODATABASE_PASSWORD=docker
      - GEONODE_GEODATABASE=gis
      - PGPASSWORD=docker
    links:
      - db
      - rabbitmq
    network_mode: "bridge"

  web:
    image: nginx
    command: prod
    entrypoint: /etc/nginx/sites-available/docker-entrypoint.sh
    volumes:
      # I dont use volumes_from as I want to use the ro modifier
      - './production/docker/nginx_conf/sites-available:/etc/nginx/sites-available'
      - '../src/geonode/geonode/static_root:/home/web/static:ro'
      - '../src/geonode/geonode/uploaded:/home/web/media:ro'
      - './logs:/var/log/nginx'
    links:
      - django
#  Default exposed port.
#  Should be specified in docker-compose.override.yml
#    ports:
#      - "80:80"
    network_mode: "bridge"

  celery:
    build: docker-geonode
    restart: on-failure
    working_dir: /usr/src/app
    volumes:
      - '../src/geonode:/usr/src/app'
      - '../src/core:/usr/src/core'
    environment:
      - DEBUG=False
      - C_FORCE_ROOT=True
      - DATABASE_URL=postgres://gis:docker@db:5432/gis
      - GEODATABASE_URL=postgres://gis:docker@db:5432/gis
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - PYTHONPATH=/usr/src:/usr/src/app/
      - DJANGO_SETTINGS_MODULE=core.settings
      - ROOT_URLCONF=core.urls
      - SITEURL=http://localhost/
      - GEONODE_BASE_URL=http://nginx/
      - QGIS_SERVER_URL=http://qgis-server/
      - GEONODE_DATABASE_PASSWORD=docker
      - GEONODE_DATABASE=gis
      - GEONODE_GEODATABASE_PASSWORD=docker
      - GEONODE_GEODATABASE=gis
      - PGPASSWORD=docker
    command: celery -A geonode worker -l debug -Q default,cleanup,email,update,geosafe -n geonode.%h -B
    links:
      - rabbitmq
      - db
    network_mode: "bridge"
